name: "Google Cloud Storage Bucket Sync Root (GCP,GCS)"
description: "Sync a directory from a Github repository with a Google Cloud Storage (GCS) bucket"
author: "maxletourneur"

inputs:
  secrets:
    description: Google credentials
    required: true
  bucket:
    description: Bucket name
    required: true
  sync_dir_from:
    description: Repository Directory path to sync
    required: false
    default: ""
  sync_dir_to:
    description: Bucket Directory path to sync to
    required: false
    default: ""
  exclude:
    description: Regex for excluding files/dirs
    required: false
    default: ".git$"

runs:
  using: docker
  image: Dockerfile
branding:
  icon: arrow-up
  color: gray-dark
